server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: RequestHeader
              args:
                name: Authorization
                value: Bearer {jwt}
            - StripPrefix=1
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=1
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**
          filters:
            - StripPrefix=1
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

security:
  oauth2:
    resource-server:
      jwt:
        issuer-uri: http://localhost:8081/auth/realms/smart-library-realm