server:
  port: 8083

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: book_admin
    password: book_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  oauth2:
    resource-server:
      jwt:
        issuer-uri: http://localhost:8081/auth/realms/smart-library-realm