server:
  port: 8084

spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:postgresql://localhost:5432/loan_db
    username: loan_admin
    password: loan_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  oauth2:
    resource-server:
      jwt:
        issuer-uri: http://localhost:8081/auth/realms/smart-library-realm

resilience4j:
  circuitbreaker:
    instances:
      bookService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
  retry:
    instances:
      bookService:
        max-attempts: 3
        wait-duration: 2s

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic